parameters:
  - name: dependsOn
    type: object
    default: []
  - name: azureSubscription
    type: string
  - name: environment
    type: string
  - name: environmentName
    type: string

jobs:
  - deployment: validate_bicep_against_${{ parameters.environmentName }}_environment
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              name: RunPreflightValidation
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: "pscore"
                scriptLocation: "inlineScript"
                inlineScript: |
                  $config = (Get-Content params/${{ parameters.environmentName }}.json | ConvertFrom-Json)

                  az deployment sub validate `
                    --name 'geolocation${{ parameters.environmentName }}' `
                    --template-file ./bicep/main.bicep `
                    --location $config.parameters.parLocation.value `
                    --parameters params/${{ parameters.environmentName }}.json `
                        parKeyVaultCreateMode='recover'

                  az deployment sub validate `
                    --name 'geolocationconsumers${{ parameters.environmentName }}' `
                    --template-file ./bicep/apiConsumers.bicep `
                    --location $config.parameters.parLocation.value `
                    --parameters params/apiConsumers.${{ parameters.environmentName }}.json


            - task: AzureCLI@2
              name: RunWhatIfDeploy
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: "pscore"
                scriptLocation: "inlineScript"
                inlineScript: |
                  $config = (Get-Content params/${{ parameters.environmentName }}.json | ConvertFrom-Json)

                  az deployment sub what-if `
                    --name 'geolocation${{ parameters.environmentName }}' `
                    --template-file ./bicep/main.bicep `
                    --location $config.parameters.parLocation.value `
                    --parameters @params/${{ parameters.environmentName }}.json `
                        parKeyVaultCreateMode='recover'

                  az deployment sub what-if `
                    --name 'geolocationconsumers${{ parameters.environmentName }}' `
                    --template-file ./bicep/apiConsumers.bicep `
                    --location $config.parameters.parLocation.value `
                    --parameters @params/apiConsumers.${{ parameters.environmentName }}.json
