parameters:
  - name: environmentName
    type: string
  - name: siteUrl
    type: string

stages:
  - stage: run_ui_tests_against_${{ parameters.environmentName }}
    jobs:
      - job: run_ui_tests

        workspace:
          clean: all

        variables:
          - name: SITE_URL
            value: "${{ parameters.siteUrl }}"

        steps:
          - pwsh: Invoke-WebRequest -Uri ${{ parameters.siteUrl }} -MaximumRetryCount 10 -RetryIntervalSec 5

          - task: UseDotNet@2
            displayName: "Use .NET SDK 7.x"
            inputs:
              version: "7.x"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - Release"
            inputs:
              command: "build"
              arguments: "--configuration Release"
              projects: "$(System.DefaultWorkingDirectory)/**/*.IntegrationTests.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Run UI Tests"
            inputs:
              command: "test"
              arguments: "--no-build --configuration Release"
              publishTestResults: true
              projects: "$(System.DefaultWorkingDirectory)/**/*.IntegrationTests.csproj"
