trigger:
  branches:
    include:
      - "integration/*"

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

variables:
  buildConfiguration: "Release"
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    nugetPackageVersion: "1.1.$(Build.BuildNumber)"
  ${{ else }}:
    nugetPackageVersion: "1.1.$(Build.BuildNumber)-preview"

stages:
  - template: templates/execute-ui-tests.yml
    parameters:
      environmentName: "dev"
      siteUrl: "https://dev.geo-location.net"
