trigger: none

pr:
  autoCancel: false
  branches:
    include:
      - "main"

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

variables:
  buildConfiguration: "Release"
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    nugetPackageVersion: "1.1.$(Build.BuildNumber)"
  ${{ else }}:
    nugetPackageVersion: "1.1.$(Build.BuildNumber)-preview"

stages:
  - stage: build
    jobs:
      - template: jobs/build-net-core-projects.yml@ado-pipeline-templates
        parameters:
          jobName: "BuildNetCoreProjects"
          toolsManifestPath: "$(Build.SourcesDirectory)/.config/dotnet-tools.json"
          useCobertura: true
          buildConfiguration: $(buildConfiguration)
          dotnetSdkVersion: "9.x"
          additionalBuildSteps:
            - task: DotNetCoreCLI@2
              displayName: "Publish MX.GeoLocation.Web project"
              inputs:
                command: "publish"
                publishWebProjects: false
                projects: "**/MX.GeoLocation.Web.csproj"
                arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/MX.GeoLocation.Web.zip"
            - task: DotNetCoreCLI@2
              displayName: "Publish MX.GeoLocation.Api.V1 project"
              inputs:
                command: "publish"
                publishWebProjects: false
                projects: "**/MX.GeoLocation.Api.V1.csproj"
                arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/MX.GeoLocation.Api.V1.zip"
            - task: DotNetCoreCLI@2
              displayName: "Pack MX.GeoLocation.Api.Client.V1 project"
              inputs:
                command: custom
                custom: pack
                arguments: >
                  $(Build.SourcesDirectory)\src\MX.GeoLocation.Api.Client.V1\MX.GeoLocation.Api.Client.V1.csproj --output $(Build.ArtifactStagingDirectory)/packages /p:Configuration=$(buildConfiguration) /p:PackageVersion=$(nugetPackageVersion) --verbosity Detailed
            - task: DotNetCoreCLI@2
              displayName: "Pack MX.GeoLocation.Abstractions.V1 project"
              inputs:
                command: custom
                custom: pack
                arguments: >
                  $(Build.SourcesDirectory)\src\MX.GeoLocation.Abstractions.V1\MX.GeoLocation.Abstractions.V1.csproj --output $(Build.ArtifactStagingDirectory)/packages /p:Configuration=$(buildConfiguration) /p:PackageVersion=$(nugetPackageVersion) --verbosity Detailed
          additionalPublishSteps:
            - publish: "$(Build.artifactStagingDirectory)/MX.GeoLocation.Web.zip"
              displayName: "Publish MX.GeoLocation.Web artifact"
              artifact: MX.GeoLocation.Web
            - publish: "$(Build.artifactStagingDirectory)/MX.GeoLocation.Api.V1.zip"
              displayName: "Publish MX.GeoLocation.Api.V1 artifact"
              artifact: MX.GeoLocation.Api.V1
            - publish: "$(Build.artifactStagingDirectory)/packages"
              displayName: "Publish NuGet Packages artifact"
              artifact: nuget-packages

      - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
        parameters:
          jobName: "bicep_linter"
          azureSubscription: "spn-geo-location-development"

      - template: templates/bicep-environment-validation.yml
        parameters:
          dependsOn: [bicep_linter]
          azureSubscription: "spn-geo-location-development"
          environment: geo-location-Development
          environmentName: "dev"

      - template: jobs/devops-secure-scanning.yml@ado-pipeline-templates
        parameters:
          dependsOn: [bicep_linter]
        
      - template: templates/bicep-environment-validation.yml
        parameters:
          dependsOn: [bicep_linter]
          azureSubscription: "spn-geo-location-production"
          environment: geo-location-Production
          environmentName: "prd"

  - template: templates/deploy-environment.yml
    parameters:
      azureSubscription: "spn-geo-location-development"
      environment: geo-location-Development
      environmentName: "dev"
      webAppsEnvironment: geo-location-Development
      siteUrl: "https://dev.geo-location.net"
