resources:
  pipelines:
    - pipeline: geo-location.ReleaseToProduction
      source: geo-location.ReleaseToProduction
      project: Personal-Public
      trigger: true
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: validate
    jobs:
      - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
        parameters:
          jobName: "bicep_linter"
          azureSubscription: "spn-geo-location-development"
          
      - template: templates/bicep-environment-validation.yml
        parameters:
          dependsOn: [bicep_linter]
          azureSubscription: "spn-geo-location-development"
          environment: geo-location-Development
          environmentName: "dev"

      - template: templates/bicep-environment-validation.yml
        parameters:
          dependsOn: [bicep_linter, validate_bicep_against_dev_environment]
          azureSubscription: "spn-geo-location-production"
          environment: geo-location-Production
          environmentName: "prd"

  - template: templates/deploy-environment-consumers.yml
    parameters:
      azureSubscription: "spn-geo-location-development"
      environment: geo-location-Development
      environmentName: "dev"

  - template: templates/deploy-environment-consumers.yml
    parameters:
      azureSubscription: "spn-geo-location-production"
      environment: geo-location-Production
      environmentName: "prd"
