name: Feature Development

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/*"

permissions:
  contents: read # This is required for actions/checkout

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: frasermolyneux/actions/dotnet-web-ci@main
      with:
        dotnet-project: "public-webapp"
        dotnet-version: 8.0.x
        src-folder: "src"

    - uses: frasermolyneux/actions/dotnet-web-ci@main
      with:
        dotnet-project: "lookup-webapi"
        dotnet-version: 8.0.x
        src-folder: "src"
