name: Pull Request Validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read # This is required for actions/checkout

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v4

    - name: "Dependency Review"
      uses: actions/dependency-review-action@v4

  dotnet-func-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: frasermolyneux/actions/dotnet-web-ci@main
      with:
        dotnet-project: "public-webapp"
        dotnet-version: 8.0.x
        src-folder: "src"

    - uses: frasermolyneux/actions/dotnet-web-ci@main
      with:
        dotnet-project: "lookup-webapi"
        dotnet-version: 8.0.x
        src-folder: "src"
